CREATE TABLE TBL_ESTABELECIMENTO
   ("ID_ESTABELECIMENTO" NUMBER(38,0),
	"NOME_ESTABELECIMENTO" VARCHAR2(50 BYTE), 
	"DH_CRIACAO" TIMESTAMP (6) WITH TIME ZONE, 
	"ID_TIPO_ESTABELECIMENTO" NUMBER(38,0));
    
ALTER TABLE TBL_ESTABELECIMENTO ADD CONSTRAINTS ID_TIPO_ESTABELECIMENTO_FK FOREIGN KEY(ID_TIPO_ESTABELECIMENTO) 
REFERENCES TIPO_ESTABELECIMENTO(ID_TIPO_ESTABELECIMENTO);


CREATE SEQUENCE  TB_ESTABELECIMENTO_SEQ  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;


CREATE SEQUENCE  TIPO_ESTABELECIMENTO_SEQ  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;

CREATE TABLE TIPO_ESTABELECIMENTO
   ("ID_TIPO_ESTABELECIMENTO" NUMBER(38,0) NOT NULL ENABLE PRIMARY KEY, 
	"NOME_TIPO_ESTABELECIMENTO" VARCHAR2(50 BYTE));